///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ragnarok.UserInterface.Game
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Add_SignManually recording.
    /// </summary>
    [TestModule("18e2334e-240e-4412-baa6-5a5e3d8fcbb5", ModuleType.Recording, 1)]
    public partial class Add_SignManually : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Ragnarok.ObjectRepository repository.
        /// </summary>
        public static global::Ragnarok.ObjectRepository repo = global::Ragnarok.ObjectRepository.Instance;

        static Add_SignManually instance = new Add_SignManually();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Add_SignManually()
        {
            txt_SignName = "test friendly name";
            txt_sign_friendlyName = "test sign name";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Add_SignManually Instance
        {
            get { return instance; }
        }

#region Variables

        string _txt_sign_friendlyName;

        /// <summary>
        /// Gets or sets the value of variable txt_sign_friendlyName.
        /// </summary>
        [TestVariable("d753f9d7-8c9a-428f-98b5-58866a0c2029")]
        public string txt_sign_friendlyName
        {
            get { return _txt_sign_friendlyName; }
            set { _txt_sign_friendlyName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable txt_SignName.
        /// </summary>
        [TestVariable("2765821b-f77a-4f82-bc98-8001b4c11d54")]
        public string txt_SignName
        {
            get { return repo.txt_SignName; }
            set { repo.txt_SignName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Games.AddANewSign' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.Games.AddANewSignInfo, new RecordItemIndex(0));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Games.AddANewSign.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Games.CheckBox_Sign_Edit' at 5;15.", repo.Vertex.AristocratVertexWebUI.Form143077288.Games.CheckBox_Sign_EditInfo, new RecordItemIndex(1));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Games.CheckBox_Sign_Edit.Click("5;15");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.ContentElement_SignName' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.ContentElement_SignNameInfo, new RecordItemIndex(2));
            //repo.Vertex.AristocratVertexWebUI.Form143077288.ContentElement_SignName.Click();
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$txt_SignName' on item 'Vertex.AristocratVertexWebUI.Form143077288.ContentElement_SignName'.", repo.Vertex.AristocratVertexWebUI.Form143077288.ContentElement_SignNameInfo, new RecordItemIndex(3));
            //repo.Vertex.AristocratVertexWebUI.Form143077288.ContentElement_SignName.Element.SetAttributeValue("Text", txt_SignName);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Games.Sign_name' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.Games.Sign_nameInfo, new RecordItemIndex(4));
            //repo.Vertex.AristocratVertexWebUI.Form143077288.Games.Sign_name.Click();
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$txt_SignName' on item 'Vertex.AristocratVertexWebUI.Form143077288.Games.Sign_name'.", repo.Vertex.AristocratVertexWebUI.Form143077288.Games.Sign_nameInfo, new RecordItemIndex(5));
            //repo.Vertex.AristocratVertexWebUI.Form143077288.Games.Sign_name.Element.SetAttributeValue("Text", txt_SignName);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Games.txtSignUrl' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.Games.txtSignUrlInfo, new RecordItemIndex(6));
            //repo.Vertex.AristocratVertexWebUI.Form143077288.Games.txtSignUrl.Click();
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$txt_sign_friendlyName' on item 'Vertex.AristocratVertexWebUI.Form143077288.Games.txtSignUrl'.", repo.Vertex.AristocratVertexWebUI.Form143077288.Games.txtSignUrlInfo, new RecordItemIndex(7));
            //repo.Vertex.AristocratVertexWebUI.Form143077288.Games.txtSignUrl.Element.SetAttributeValue("Text", txt_sign_friendlyName);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Vertex.AristocratVertexWebUI'.", repo.Vertex.AristocratVertexWebUI.SelfInfo, new RecordItemIndex(8));
            //repo.Vertex.AristocratVertexWebUI.Self.EnsureVisible();
            //Keyboard.Press("{Tab}");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$txt_SignName) on item 'Vertex.AristocratVertexWebUI.Form143077288.Games.Sign_name'.", repo.Vertex.AristocratVertexWebUI.Form143077288.Games.Sign_nameInfo, new RecordItemIndex(9));
            //Validate.AttributeEqual(repo.Vertex.AristocratVertexWebUI.Form143077288.Games.Sign_nameInfo, "Text", txt_SignName);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$txt_sign_friendlyName) on item 'Vertex.AristocratVertexWebUI.Form143077288.Games.txtSignUrl'.", repo.Vertex.AristocratVertexWebUI.Form143077288.Games.txtSignUrlInfo, new RecordItemIndex(10));
            //Validate.AttributeEqual(repo.Vertex.AristocratVertexWebUI.Form143077288.Games.txtSignUrlInfo, "Text", txt_sign_friendlyName);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.ContentElement2' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.ContentElement2Info, new RecordItemIndex(11));
            repo.Vertex.AristocratVertexWebUI.Form143077288.ContentElement2.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$txt_SignName' with focus on 'Vertex.AristocratVertexWebUI'.", repo.Vertex.AristocratVertexWebUI.SelfInfo, new RecordItemIndex(12));
            repo.Vertex.AristocratVertexWebUI.Self.EnsureVisible();
            Keyboard.Press(txt_SignName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Games.txtSignUrl' at UpperRight.", repo.Vertex.AristocratVertexWebUI.Form143077288.Games.txtSignUrlInfo, new RecordItemIndex(13));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Games.txtSignUrl.Click(Location.UpperRight);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'Vertex.AristocratVertexWebUI'.", repo.Vertex.AristocratVertexWebUI.SelfInfo, new RecordItemIndex(14));
            Keyboard.PrepareFocus(repo.Vertex.AristocratVertexWebUI.Self);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'Vertex.AristocratVertexWebUI'.", repo.Vertex.AristocratVertexWebUI.SelfInfo, new RecordItemIndex(15));
            repo.Vertex.AristocratVertexWebUI.Self.EnsureVisible();
            Keyboard.Press("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$txt_sign_friendlyName' with focus on 'Vertex.AristocratVertexWebUI'.", repo.Vertex.AristocratVertexWebUI.SelfInfo, new RecordItemIndex(16));
            repo.Vertex.AristocratVertexWebUI.Self.EnsureVisible();
            Keyboard.Press(txt_sign_friendlyName);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
