///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ragnarok.UserInterface.Game
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddGame recording.
    /// </summary>
    [TestModule("bcb3eb91-f496-4a98-889a-1b7483fc6157", ModuleType.Recording, 1)]
    public partial class AddGame : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Ragnarok.ObjectRepository repository.
        /// </summary>
        public static global::Ragnarok.ObjectRepository repo = global::Ragnarok.ObjectRepository.Instance;

        static AddGame instance = new AddGame();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddGame()
        {
            varGameName = "na";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddGame Instance
        {
            get { return instance; }
        }

#region Variables

        string _varGameName;

        /// <summary>
        /// Gets or sets the value of variable varGameName.
        /// </summary>
        [TestVariable("f10afd61-b9eb-4bd3-a890-c1389ba052ac")]
        public string varGameName
        {
            get { return _varGameName; }
            set { _varGameName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.AddANewGame' at 55;7.", repo.Vertex.AristocratVertexWebUI.Form143077288.AddANewGameInfo, new RecordItemIndex(0));
            repo.Vertex.AristocratVertexWebUI.Form143077288.AddANewGame.Click("55;7");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.ContentElement' at 127;12.", repo.Vertex.AristocratVertexWebUI.Form143077288.ContentElementInfo, new RecordItemIndex(1));
            //repo.Vertex.AristocratVertexWebUI.Form143077288.ContentElement.Click("127;12");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varGameName' with focus on 'Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.TextBox2'.", repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.TextBox2Info, new RecordItemIndex(2));
            //repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.TextBox2.PressKeys(varGameName);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Casino.AddNewCasino.Save' at 9;12.", repo.Vertex.AristocratVertexWebUI.Form143077288.Casino.AddNewCasino.SaveInfo, new RecordItemIndex(3));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Casino.AddNewCasino.Save.Click("9;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 30s.", new RecordItemIndex(4));
            Delay.Duration(30000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
