///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ragnarok.UserInterface.Game
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Edit_SignFriendlyName recording.
    /// </summary>
    [TestModule("4f2cd48e-4a1f-41a5-8dc6-4773e5a5709f", ModuleType.Recording, 1)]
    public partial class Edit_SignFriendlyName : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Ragnarok.ObjectRepository repository.
        /// </summary>
        public static global::Ragnarok.ObjectRepository repo = global::Ragnarok.ObjectRepository.Instance;

        static Edit_SignFriendlyName instance = new Edit_SignFriendlyName();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Edit_SignFriendlyName()
        {
            txt_sign_friendlyName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Edit_SignFriendlyName Instance
        {
            get { return instance; }
        }

#region Variables

        string _txt_sign_friendlyName;

        /// <summary>
        /// Gets or sets the value of variable txt_sign_friendlyName.
        /// </summary>
        [TestVariable("8a180eb2-299d-49a0-86c4-6903478a13db")]
        public string txt_sign_friendlyName
        {
            get { return _txt_sign_friendlyName; }
            set { _txt_sign_friendlyName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.Edit' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.EditInfo, new RecordItemIndex(0));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.Edit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$txt_sign_friendlyName' on item 'Vertex.AristocratVertexWebUI.Form143077288.Games.SignFriendlyName'.", repo.Vertex.AristocratVertexWebUI.Form143077288.Games.SignFriendlyNameInfo, new RecordItemIndex(1));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Games.SignFriendlyName.Element.SetAttributeValue("Text", txt_sign_friendlyName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$txt_sign_friendlyName) on item 'Vertex.AristocratVertexWebUI.Form143077288.Games.SignFriendlyName'.", repo.Vertex.AristocratVertexWebUI.Form143077288.Games.SignFriendlyNameInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.Vertex.AristocratVertexWebUI.Form143077288.Games.SignFriendlyNameInfo, "Text", txt_sign_friendlyName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Vertex.AristocratVertexWebUI'.", repo.Vertex.AristocratVertexWebUI.SelfInfo, new RecordItemIndex(3));
            repo.Vertex.AristocratVertexWebUI.Self.EnsureVisible();
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
