///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ragnarok.UserInterface.Game
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Open_ScreenSign recording.
    /// </summary>
    [TestModule("192326c5-e3c5-4ca6-91fe-860018e30930", ModuleType.Recording, 1)]
    public partial class Open_ScreenSign : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Ragnarok.ObjectRepository repository.
        /// </summary>
        public static global::Ragnarok.ObjectRepository repo = global::Ragnarok.ObjectRepository.Instance;

        static Open_ScreenSign instance = new Open_ScreenSign();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Open_ScreenSign()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Open_ScreenSign Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Valid='True') on item 'Vertex.AristocratVertexWebUI.Form143077288.Games.Signs_menu'.", repo.Vertex.AristocratVertexWebUI.Form143077288.Games.Signs_menuInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.Vertex.AristocratVertexWebUI.Form143077288.Games.Signs_menuInfo, "Valid", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Signs') on item 'Vertex.AristocratVertexWebUI.Form143077288.Games.Signs_menu'.", repo.Vertex.AristocratVertexWebUI.Form143077288.Games.Signs_menuInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.Vertex.AristocratVertexWebUI.Form143077288.Games.Signs_menuInfo, "Text", "Signs");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Games.Signs_menu' at 11;7.", repo.Vertex.AristocratVertexWebUI.Form143077288.Games.Signs_menuInfo, new RecordItemIndex(2));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Games.Signs_menu.Click("11;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'Vertex.AristocratVertexWebUI.Form143077288.Games.AddANewSign'.", repo.Vertex.AristocratVertexWebUI.Form143077288.Games.AddANewSignInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.Vertex.AristocratVertexWebUI.Form143077288.Games.AddANewSignInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Add a new sign') on item 'Vertex.AristocratVertexWebUI.Form143077288.Games.AddANewSign'.", repo.Vertex.AristocratVertexWebUI.Form143077288.Games.AddANewSignInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.Vertex.AristocratVertexWebUI.Form143077288.Games.AddANewSignInfo, "Text", "Add a new sign");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
