///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ragnarok.UserInterface.Game
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TEST_AddGame recording.
    /// </summary>
    [TestModule("c86c1f74-a867-490d-84d4-918b14d641e3", ModuleType.Recording, 1)]
    public partial class TEST_AddGame : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Ragnarok.ObjectRepository repository.
        /// </summary>
        public static global::Ragnarok.ObjectRepository repo = global::Ragnarok.ObjectRepository.Instance;

        static TEST_AddGame instance = new TEST_AddGame();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TEST_AddGame()
        {
            varGameName = "TEST2";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TEST_AddGame Instance
        {
            get { return instance; }
        }

#region Variables

        string _varGameName;

        /// <summary>
        /// Gets or sets the value of variable varGameName.
        /// </summary>
        [TestVariable("f2f29269-d717-4cb8-a3f7-e366a7d3c7d5")]
        public string varGameName
        {
            get { return _varGameName; }
            set { _varGameName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.AddANewGame' at 116;22.", repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.AddANewGameInfo, new RecordItemIndex(0));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.AddANewGame.Click("116;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.ContentElement' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.ContentElementInfo, new RecordItemIndex(1));
            repo.Vertex.AristocratVertexWebUI.Form143077288.ContentElement.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'Vertex.AristocratVertexWebUI'.", repo.Vertex.AristocratVertexWebUI.SelfInfo, new RecordItemIndex(2));
            Keyboard.PrepareFocus(repo.Vertex.AristocratVertexWebUI.Self);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'Vertex.AristocratVertexWebUI'.", repo.Vertex.AristocratVertexWebUI.SelfInfo, new RecordItemIndex(3));
            repo.Vertex.AristocratVertexWebUI.Self.EnsureVisible();
            Keyboard.Press("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varGameName' with focus on 'Vertex.AristocratVertexWebUI'.", repo.Vertex.AristocratVertexWebUI.SelfInfo, new RecordItemIndex(4));
            repo.Vertex.AristocratVertexWebUI.Self.EnsureVisible();
            Keyboard.Press(varGameName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Vertex.AristocratVertexWebUI'.", repo.Vertex.AristocratVertexWebUI.SelfInfo, new RecordItemIndex(5));
            repo.Vertex.AristocratVertexWebUI.Self.EnsureVisible();
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Casino.AddNewCasino.Save' at 47;8.", repo.Vertex.AristocratVertexWebUI.Form143077288.Casino.AddNewCasino.SaveInfo, new RecordItemIndex(6));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Casino.AddNewCasino.Save.Click("47;8");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
