///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ragnarok.UserInterface.Game
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TEST_AddSign recording.
    /// </summary>
    [TestModule("34e6fce9-8fc8-41d3-b5a6-3ceb7f9e3097", ModuleType.Recording, 1)]
    public partial class TEST_AddSign : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Ragnarok.ObjectRepository repository.
        /// </summary>
        public static global::Ragnarok.ObjectRepository repo = global::Ragnarok.ObjectRepository.Instance;

        static TEST_AddSign instance = new TEST_AddSign();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TEST_AddSign()
        {
            txt_SignName = "SIGN NAME";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TEST_AddSign Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable txt_SignName.
        /// </summary>
        [TestVariable("306c0011-fa30-44d6-8f2e-de1d31be74fe")]
        public string txt_SignName
        {
            get { return repo.txt_SignName; }
            set { repo.txt_SignName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Games.AddANewSign' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.Games.AddANewSignInfo, new RecordItemIndex(0));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Games.AddANewSign.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Games.CheckBox_Sign_Edit' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.Games.CheckBox_Sign_EditInfo, new RecordItemIndex(1));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Games.CheckBox_Sign_Edit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.ContentElement_SignName' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.ContentElement_SignNameInfo, new RecordItemIndex(2));
            repo.Vertex.AristocratVertexWebUI.Form143077288.ContentElement_SignName.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$txt_SignName' with focus on 'Vertex.AristocratVertexWebUI'.", repo.Vertex.AristocratVertexWebUI.SelfInfo, new RecordItemIndex(3));
            repo.Vertex.AristocratVertexWebUI.Self.EnsureVisible();
            Keyboard.Press(txt_SignName);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Games.txtSignUrl' at UpperRight.", repo.Vertex.AristocratVertexWebUI.Form143077288.Games.txtSignUrlInfo, new RecordItemIndex(4));
            //repo.Vertex.AristocratVertexWebUI.Form143077288.Games.txtSignUrl.Click(Location.UpperRight);
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'Vertex.AristocratVertexWebUI'.", repo.Vertex.AristocratVertexWebUI.SelfInfo, new RecordItemIndex(5));
            repo.Vertex.AristocratVertexWebUI.Self.EnsureVisible();
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
