///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ragnarok.UserInterface.EGM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddEGM recording.
    /// </summary>
    [TestModule("2cc3099e-f462-4412-8adb-79f10c8d102f", ModuleType.Recording, 1)]
    public partial class AddEGM : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Ragnarok.ObjectRepository repository.
        /// </summary>
        public static global::Ragnarok.ObjectRepository repo = global::Ragnarok.ObjectRepository.Instance;

        static AddEGM instance = new AddEGM();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddEGM()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddEGM Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.NavigationControl1.EGMs' at Center.", repo.Vertex.AristocratVertexWebUI.NavigationControl1.EGMsInfo, new RecordItemIndex(0));
            repo.Vertex.AristocratVertexWebUI.NavigationControl1.EGMs.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.AddAnEgmManually' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.AddAnEgmManuallyInfo, new RecordItemIndex(1));
            repo.Vertex.AristocratVertexWebUI.Form143077288.AddAnEgmManually.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ATI_1234'.", new RecordItemIndex(2));
            Keyboard.Press("ATI_1234");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Legacy_Signs.drpDisplay' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.Legacy_Signs.drpDisplayInfo, new RecordItemIndex(3));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Legacy_Signs.drpDisplay.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Legacy_Signs.AristocratVertexUIModelSignDisplay' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.Legacy_Signs.AristocratVertexUIModelSignDisplayInfo, new RecordItemIndex(4));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Legacy_Signs.AristocratVertexUIModelSignDisplay.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Casino.AddNewCasino.Save' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.Casino.AddNewCasino.SaveInfo, new RecordItemIndex(5));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Casino.AddNewCasino.Save.Click();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.AddNewEgms' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.AddNewEgmsInfo, new RecordItemIndex(6));
            //repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.AddNewEgms.Click();
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.ATI_Gen7_CheckBox' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.ATI_Gen7_CheckBoxInfo, new RecordItemIndex(7));
            //repo.Vertex.AristocratVertexWebUI.Form143077288.ATI_Gen7_CheckBox.Click();
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Casino.AddNewCasino.Save' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.Casino.AddNewCasino.SaveInfo, new RecordItemIndex(8));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Casino.AddNewCasino.Save.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
