///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ragnarok.UserInterface.Configuration
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ChangeConfig recording.
    /// </summary>
    [TestModule("f43f0d9a-c719-4459-9537-fc31800c6c71", ModuleType.Recording, 1)]
    public partial class ChangeConfig : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Ragnarok.ObjectRepository repository.
        /// </summary>
        public static global::Ragnarok.ObjectRepository repo = global::Ragnarok.ObjectRepository.Instance;

        static ChangeConfig instance = new ChangeConfig();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ChangeConfig()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ChangeConfig Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.VertexShellMainForm.UserInterface' at 77;20.", repo.Vertex.VertexShellMainForm.UserInterfaceInfo, new RecordItemIndex(0));
            repo.Vertex.VertexShellMainForm.UserInterface.Click("77;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.NavigationControl1.Configuration' at 30;11.", repo.Vertex.AristocratVertexWebUI.NavigationControl1.ConfigurationInfo, new RecordItemIndex(1));
            repo.Vertex.AristocratVertexWebUI.NavigationControl1.Configuration.Click("30;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.TabControl' at 511;37.", repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.TabControlInfo, new RecordItemIndex(2));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.TabControl.Click("511;37");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -50 units.", new RecordItemIndex(3));
            Mouse.ScrollWheel(-50);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Configuration.Options.TurnoverValidation' at 97;9.", repo.Vertex.AristocratVertexWebUI.Form143077288.Configuration.Options.TurnoverValidationInfo, new RecordItemIndex(4));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Configuration.Options.TurnoverValidation.Click("97;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.False' at 5;20.", repo.Vertex.AristocratVertexWebUI.Form143077288.FalseInfo, new RecordItemIndex(5));
            repo.Vertex.AristocratVertexWebUI.Form143077288.False.Click("5;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Configuration.Options.Save_TimeSourceVertex' at 15;15.", repo.Vertex.AristocratVertexWebUI.Form143077288.Configuration.Options.Save_TimeSourceVertexInfo, new RecordItemIndex(6));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Configuration.Options.Save_TimeSourceVertex.Click("15;15");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.VertexAdministrator.ButtonClose' at 13;10.", repo.Vertex.VertexAdministrator.ButtonCloseInfo, new RecordItemIndex(7));
            //repo.Vertex.VertexAdministrator.ButtonClose.Click("13;10");
            //Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
