///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ragnarok.UserInterface.Configuration
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ChangeConfig2 recording.
    /// </summary>
    [TestModule("fe354c54-ed94-445f-b6ae-86bd73cde34f", ModuleType.Recording, 1)]
    public partial class ChangeConfig2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Ragnarok.ObjectRepository repository.
        /// </summary>
        public static global::Ragnarok.ObjectRepository repo = global::Ragnarok.ObjectRepository.Instance;

        static ChangeConfig2 instance = new ChangeConfig2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ChangeConfig2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ChangeConfig2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.VertexShellMainForm.UserInterface1' at 132;20.", repo.Vertex.VertexShellMainForm.UserInterface1Info, new RecordItemIndex(0));
            repo.Vertex.VertexShellMainForm.UserInterface1.Click("132;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.NavigationControl1.Configuration' at 46;9.", repo.Vertex.AristocratVertexWebUI.NavigationControl1.ConfigurationInfo, new RecordItemIndex(1));
            repo.Vertex.AristocratVertexWebUI.NavigationControl1.Configuration.Click("46;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.TabControl' at 581;4.", repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.TabControlInfo, new RecordItemIndex(2));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.TabControl.Click("581;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.VerticalLargeIncrease' at 10;119.", repo.Vertex.AristocratVertexWebUI.Form143077288.VerticalLargeIncreaseInfo, new RecordItemIndex(3));
            repo.Vertex.AristocratVertexWebUI.Form143077288.VerticalLargeIncrease.Click("10;119");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Configuration.Options.TurnoverValidation' at 83;7.", repo.Vertex.AristocratVertexWebUI.Form143077288.Configuration.Options.TurnoverValidationInfo, new RecordItemIndex(4));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Configuration.Options.TurnoverValidation.Click("83;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.False1' at 13;8.", repo.Vertex.AristocratVertexWebUI.Form143077288.False1Info, new RecordItemIndex(5));
            repo.Vertex.AristocratVertexWebUI.Form143077288.False1.Click("13;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Configuration.Options.Save_TurnoverValidation' at 12;14.", repo.Vertex.AristocratVertexWebUI.Form143077288.Configuration.Options.Save_TurnoverValidationInfo, new RecordItemIndex(6));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Configuration.Options.Save_TurnoverValidation.Click("12;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.VertexAdministrator.ButtonClose' at 15;11.", repo.Vertex.VertexAdministrator.ButtonCloseInfo, new RecordItemIndex(7));
            repo.Vertex.VertexAdministrator.ButtonClose.Click("15;11");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Save1' at 1;9.", repo.Vertex.AristocratVertexWebUI.Form143077288.Save1Info, new RecordItemIndex(8));
            //repo.Vertex.AristocratVertexWebUI.Form143077288.Save1.Click("1;9");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.VertexAdministrator.ButtonClose' at 13;10.", repo.Vertex.VertexAdministrator.ButtonCloseInfo, new RecordItemIndex(9));
            //repo.Vertex.VertexAdministrator.ButtonClose.Click("13;10");
            //Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
