///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ragnarok.UserInterface.Progressive
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddLevels recording.
    /// </summary>
    [TestModule("9af27251-8cea-4ca1-8cdc-abd129f37b83", ModuleType.Recording, 1)]
    public partial class AddLevels : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Ragnarok.ObjectRepository repository.
        /// </summary>
        public static global::Ragnarok.ObjectRepository repo = global::Ragnarok.ObjectRepository.Instance;

        static AddLevels instance = new AddLevels();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddLevels()
        {
            varLevelName = "null";
            varLevelIncRate = "null";
            varLevelInitialValue = "null";
            varLevelResetValue = "null";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddLevels Instance
        {
            get { return instance; }
        }

#region Variables

        string _varLevelName;

        /// <summary>
        /// Gets or sets the value of variable varLevelName.
        /// </summary>
        [TestVariable("0d7366cb-4109-4aec-98cc-99757fa74447")]
        public string varLevelName
        {
            get { return _varLevelName; }
            set { _varLevelName = value; }
        }

        string _varLevelIncRate;

        /// <summary>
        /// Gets or sets the value of variable varLevelIncRate.
        /// </summary>
        [TestVariable("66a70bb3-381d-46a2-ace8-93c17e00e21f")]
        public string varLevelIncRate
        {
            get { return _varLevelIncRate; }
            set { _varLevelIncRate = value; }
        }

        string _varLevelInitialValue;

        /// <summary>
        /// Gets or sets the value of variable varLevelInitialValue.
        /// </summary>
        [TestVariable("2f216517-850d-401f-9a10-cea020f746d8")]
        public string varLevelInitialValue
        {
            get { return _varLevelInitialValue; }
            set { _varLevelInitialValue = value; }
        }

        string _varLevelResetValue;

        /// <summary>
        /// Gets or sets the value of variable varLevelResetValue.
        /// </summary>
        [TestVariable("043f45fb-0b96-4a4c-abca-f6075b2a19c4")]
        public string varLevelResetValue
        {
            get { return _varLevelResetValue; }
            set { _varLevelResetValue = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.AddANewLevel' at 59;9.", repo.Vertex.AristocratVertexWebUI.Form143077288.AddANewLevelInfo, new RecordItemIndex(0));
            repo.Vertex.AristocratVertexWebUI.Form143077288.AddANewLevel.Click("59;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.ContentElement1' at 42;10.", repo.Vertex.AristocratVertexWebUI.Form143077288.ContentElement1Info, new RecordItemIndex(1));
            repo.Vertex.AristocratVertexWebUI.Form143077288.ContentElement1.Click("42;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varLevelName' with focus on 'Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.Name'.", repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.NameInfo, new RecordItemIndex(2));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.Name.PressKeys(varLevelName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.ContentElement' at 24;8.", repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.ContentElementInfo, new RecordItemIndex(3));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.ContentElement.Click("24;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varLevelIncRate' with focus on 'Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.TextBox'.", repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.TextBoxInfo, new RecordItemIndex(4));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.TextBox.PressKeys(varLevelIncRate);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.ContentElement1' at 42;14.", repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.ContentElement1Info, new RecordItemIndex(5));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.ContentElement1.Click("42;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varLevelInitialValue' with focus on 'Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.TextBox1'.", repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.TextBox1Info, new RecordItemIndex(6));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.TextBox1.PressKeys(varLevelInitialValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.ContentElement2' at 31;14.", repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.ContentElement2Info, new RecordItemIndex(7));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.ContentElement2.Click("31;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varLevelResetValue' with focus on 'Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.TextBox2'.", repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.TextBox2Info, new RecordItemIndex(8));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.TextBox2.PressKeys(varLevelResetValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Casino.AddNewCasino.Save' at 52;13.", repo.Vertex.AristocratVertexWebUI.Form143077288.Casino.AddNewCasino.SaveInfo, new RecordItemIndex(9));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Casino.AddNewCasino.Save.Click("52;13");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
