///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ragnarok.UserInterface.Progressive
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NavigateToProgressive recording.
    /// </summary>
    [TestModule("f06f89aa-d0c2-4971-b9b2-98a8298bbfc3", ModuleType.Recording, 1)]
    public partial class NavigateToProgressive : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Ragnarok.ObjectRepository repository.
        /// </summary>
        public static global::Ragnarok.ObjectRepository repo = global::Ragnarok.ObjectRepository.Instance;

        static NavigateToProgressive instance = new NavigateToProgressive();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NavigateToProgressive()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NavigateToProgressive Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Progressives') on item 'Vertex.AristocratVertexWebUI.NavigationControl1.menu_Progressives'.", repo.Vertex.AristocratVertexWebUI.NavigationControl1.menu_ProgressivesInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.Vertex.AristocratVertexWebUI.NavigationControl1.menu_ProgressivesInfo, "Text", "Progressives");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.NavigationControl1.menu_Progressives' at 60;13.", repo.Vertex.AristocratVertexWebUI.NavigationControl1.menu_ProgressivesInfo, new RecordItemIndex(1));
            repo.Vertex.AristocratVertexWebUI.NavigationControl1.menu_Progressives.Click("60;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Progressive') on item 'Vertex.AristocratVertexWebUI.Form143077288.Progressive.UI_ProgressiveTableHeader'.", repo.Vertex.AristocratVertexWebUI.Form143077288.Progressive.UI_ProgressiveTableHeaderInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.Vertex.AristocratVertexWebUI.Form143077288.Progressive.UI_ProgressiveTableHeaderInfo, "Text", "Progressive");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
