///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ragnarok.UserInterface.Progressive
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Validate_ProgressiveName recording.
    /// </summary>
    [TestModule("bdeba896-8727-4730-9a6b-d84fafb1f8ce", ModuleType.Recording, 1)]
    public partial class Validate_ProgressiveName : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Ragnarok.ObjectRepository repository.
        /// </summary>
        public static global::Ragnarok.ObjectRepository repo = global::Ragnarok.ObjectRepository.Instance;

        static Validate_ProgressiveName instance = new Validate_ProgressiveName();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Validate_ProgressiveName()
        {
            txt_ProgressiveName = "Progressive_1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Validate_ProgressiveName Instance
        {
            get { return instance; }
        }

#region Variables

        string _txt_ProgressiveName;

        /// <summary>
        /// Gets or sets the value of variable txt_ProgressiveName.
        /// </summary>
        [TestVariable("10ffa394-1149-476d-81f0-4391b95645b6")]
        public string txt_ProgressiveName
        {
            get { return _txt_ProgressiveName; }
            set { _txt_ProgressiveName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'Vertex.AristocratVertexWebUI.Form143077288.Progressive.Edit_FirstProgressive'.", repo.Vertex.AristocratVertexWebUI.Form143077288.Progressive.Edit_FirstProgressiveInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.Vertex.AristocratVertexWebUI.Form143077288.Progressive.Edit_FirstProgressiveInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.Edit' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.EditInfo, new RecordItemIndex(1));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Monitor.MonitorTabs.Edit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$txt_ProgressiveName) on item 'Vertex.AristocratVertexWebUI.Form143077288.Progressive.ProgressiveName'.", repo.Vertex.AristocratVertexWebUI.Form143077288.Progressive.ProgressiveNameInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.Vertex.AristocratVertexWebUI.Form143077288.Progressive.ProgressiveNameInfo, "Text", txt_ProgressiveName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.Casino.AddNewCasino.Cancel' at 62;12.", repo.Vertex.AristocratVertexWebUI.Form143077288.Casino.AddNewCasino.CancelInfo, new RecordItemIndex(3));
            repo.Vertex.AristocratVertexWebUI.Form143077288.Casino.AddNewCasino.Cancel.Click("62;12");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
