///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ragnarok.UserInterface.Progressive
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Validation_ProgSaveButton_Disabled recording.
    /// </summary>
    [TestModule("058b2400-3e59-4c15-8851-62a762527dc9", ModuleType.Recording, 1)]
    public partial class Validation_ProgSaveButton_Disabled : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Ragnarok.ObjectRepository repository.
        /// </summary>
        public static global::Ragnarok.ObjectRepository repo = global::Ragnarok.ObjectRepository.Instance;

        static Validation_ProgSaveButton_Disabled instance = new Validation_ProgSaveButton_Disabled();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Validation_ProgSaveButton_Disabled()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Validation_ProgSaveButton_Disabled Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='False') on item 'Vertex.AristocratVertexWebUI.Form143077288.Progressive.Btx_Save_Progressive'.", repo.Vertex.AristocratVertexWebUI.Form143077288.Progressive.Btx_Save_ProgressiveInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.Vertex.AristocratVertexWebUI.Form143077288.Progressive.Btx_Save_ProgressiveInfo, "Enabled", "False");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
