///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ragnarok
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckUI_vs_DB recording.
    /// </summary>
    [TestModule("9cf052b5-9dec-4b97-8fb4-b4f5c4fc832a", ModuleType.Recording, 1)]
    public partial class CheckUI_vs_DB : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ObjectRepository repository.
        /// </summary>
        public static ObjectRepository repo = ObjectRepository.Instance;

        static CheckUI_vs_DB instance = new CheckUI_vs_DB();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckUI_vs_DB()
        {
            varTurnoverValidationFromDB = "True";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckUI_vs_DB Instance
        {
            get { return instance; }
        }

#region Variables

        string _varTurnoverValidationFromDB;

        /// <summary>
        /// Gets or sets the value of variable varTurnoverValidationFromDB.
        /// </summary>
        [TestVariable("ef3a2a9d-1fe9-4c02-ac28-c19f9a735c7d")]
        public string varTurnoverValidationFromDB
        {
            get { return _varTurnoverValidationFromDB; }
            set { _varTurnoverValidationFromDB = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // UI Steps to change DB TurnoverValidation ConfigValue to True/False
            Report.Log(ReportLevel.Info, "Section", "UI Steps to change DB TurnoverValidation ConfigValue to True/False", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$varTurnoverValidationFromDB) on item 'Vertex.AristocratVertexWebUI.Form143077288.False2'.", repo.Vertex.AristocratVertexWebUI.Form143077288.False2Info, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.Vertex.AristocratVertexWebUI.Form143077288.False2Info, "Text", varTurnoverValidationFromDB);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
