///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ragnarok
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The fst_Login recording.
    /// </summary>
    [TestModule("0b47149b-e5e8-4c10-93c5-e8b38844e346", ModuleType.Recording, 1)]
    public partial class Fst_Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ObjectRepository repository.
        /// </summary>
        public static ObjectRepository repo = ObjectRepository.Instance;

        static Fst_Login instance = new Fst_Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Fst_Login()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Fst_Login Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.VertexShellMainForm.GroupBoxLogin.Username' at 20;5.", repo.Vertex.VertexShellMainForm.GroupBoxLogin.UsernameInfo, new RecordItemIndex(0));
            repo.Vertex.VertexShellMainForm.GroupBoxLogin.Username.Click("20;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fst' with focus on 'Vertex.VertexShellMainForm.GroupBoxLogin.Username'.", repo.Vertex.VertexShellMainForm.GroupBoxLogin.UsernameInfo, new RecordItemIndex(1));
            repo.Vertex.VertexShellMainForm.GroupBoxLogin.Username.PressKeys("fst");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.VertexShellMainForm.GroupBoxLogin.Password' at 43;5.", repo.Vertex.VertexShellMainForm.GroupBoxLogin.PasswordInfo, new RecordItemIndex(2));
            repo.Vertex.VertexShellMainForm.GroupBoxLogin.Password.Click("43;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Atifst1' with focus on 'Vertex.VertexShellMainForm.GroupBoxLogin.Password'.", repo.Vertex.VertexShellMainForm.GroupBoxLogin.PasswordInfo, new RecordItemIndex(3));
            repo.Vertex.VertexShellMainForm.GroupBoxLogin.Password.PressKeys("Atifst1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.VertexShellMainForm.GroupBoxLogin.BtnLogin' at 43;13.", repo.Vertex.VertexShellMainForm.GroupBoxLogin.BtnLoginInfo, new RecordItemIndex(4));
            repo.Vertex.VertexShellMainForm.GroupBoxLogin.BtnLogin.Click("43;13");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
