///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ragnarok
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording_Misc recording.
    /// </summary>
    [TestModule("4a55130e-178a-4858-ae83-9f25b47deb6c", ModuleType.Recording, 1)]
    public partial class Recording_Misc : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ObjectRepository repository.
        /// </summary>
        public static ObjectRepository repo = ObjectRepository.Instance;

        static Recording_Misc instance = new Recording_Misc();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording_Misc()
        {
            UserName = "x";
            Password = "A";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording_Misc Instance
        {
            get { return instance; }
        }

#region Variables

        string _Password;

        /// <summary>
        /// Gets or sets the value of variable Password.
        /// </summary>
        [TestVariable("4bffd87a-91e3-4717-8193-bc1ac9bcd8d8")]
        public string Password
        {
            get { return _Password; }
            set { _Password = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable UserName.
        /// </summary>
        [TestVariable("bacaab02-1a8e-475f-b9ca-a6102bd9fb68")]
        public string UserName
        {
            get { return repo.Username; }
            set { repo.Username = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.VertexShellMainForm.GroupBoxLogin.Username' at 20;8.", repo.Vertex.VertexShellMainForm.GroupBoxLogin.UsernameInfo, new RecordItemIndex(0));
            repo.Vertex.VertexShellMainForm.GroupBoxLogin.Username.Click("20;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$UserName' with focus on 'Vertex.VertexShellMainForm.GroupBoxLogin.Username'.", repo.Vertex.VertexShellMainForm.GroupBoxLogin.UsernameInfo, new RecordItemIndex(1));
            repo.Vertex.VertexShellMainForm.GroupBoxLogin.Username.PressKeys(UserName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.VertexShellMainForm.GroupBoxLogin.Password' at 47;8.", repo.Vertex.VertexShellMainForm.GroupBoxLogin.PasswordInfo, new RecordItemIndex(2));
            repo.Vertex.VertexShellMainForm.GroupBoxLogin.Password.Click("47;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Password' with focus on 'Vertex.VertexShellMainForm.GroupBoxLogin.Password'.", repo.Vertex.VertexShellMainForm.GroupBoxLogin.PasswordInfo, new RecordItemIndex(3));
            repo.Vertex.VertexShellMainForm.GroupBoxLogin.Password.PressKeys(Password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.VertexShellMainForm.GroupBoxLogin.BtnLogin' at 46;14.", repo.Vertex.VertexShellMainForm.GroupBoxLogin.BtnLoginInfo, new RecordItemIndex(4));
            repo.Vertex.VertexShellMainForm.GroupBoxLogin.BtnLogin.Click("46;14");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
