///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ragnarok
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SelectJurisdiction_CA recording.
    /// </summary>
    [TestModule("9597f314-e91e-404e-aeb8-b21114861e8b", ModuleType.Recording, 1)]
    public partial class SelectJurisdiction_CA : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ObjectRepository repository.
        /// </summary>
        public static ObjectRepository repo = ObjectRepository.Instance;

        static SelectJurisdiction_CA instance = new SelectJurisdiction_CA();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SelectJurisdiction_CA()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SelectJurisdiction_CA Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.VertexShellMainForm.UserInterface' at Center.", repo.Vertex.VertexShellMainForm.UserInterfaceInfo, new RecordItemIndex(0));
            repo.Vertex.VertexShellMainForm.UserInterface.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.ComboBox' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.ComboBoxInfo, new RecordItemIndex(1));
            repo.Vertex.AristocratVertexWebUI.Form143077288.ComboBox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.CaliforniaCALIFOR' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.CaliforniaCALIFORInfo, new RecordItemIndex(2));
            repo.Vertex.AristocratVertexWebUI.Form143077288.CaliforniaCALIFOR.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.AristocratVertexWebUI.Form143077288.TextOK' at Center.", repo.Vertex.AristocratVertexWebUI.Form143077288.TextOKInfo, new RecordItemIndex(3));
            repo.Vertex.AristocratVertexWebUI.Form143077288.TextOK.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='California[CALIFOR]') on item 'Vertex.AristocratVertexWebUI.Form143077288.CaliforniaCALIFOR1'.", repo.Vertex.AristocratVertexWebUI.Form143077288.CaliforniaCALIFOR1Info, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.Vertex.AristocratVertexWebUI.Form143077288.CaliforniaCALIFOR1Info, "Text", "California[CALIFOR]");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
