///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ragnarok
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StopController recording.
    /// </summary>
    [TestModule("31ee4f11-17d4-4982-b51a-de43c7f71cdb", ModuleType.Recording, 1)]
    public partial class StopController : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ObjectRepository repository.
        /// </summary>
        public static ObjectRepository repo = ObjectRepository.Instance;

        static StopController instance = new StopController();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StopController()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StopController Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.VertexShellMainForm.Controller' at 115;19.", repo.Vertex.VertexShellMainForm.ControllerInfo, new RecordItemIndex(0));
            repo.Vertex.VertexShellMainForm.Controller.Click("115;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.ControllerSetup.ButtonStopController' at 18;8.", repo.Vertex.ControllerSetup.ButtonStopControllerInfo, new RecordItemIndex(1));
            repo.Vertex.ControllerSetup.ButtonStopController.Click("18;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.StartingController.ButtonNo' at 29;14.", repo.Vertex.StartingController.ButtonNoInfo, new RecordItemIndex(2));
            repo.Vertex.StartingController.ButtonNo.Click("29;14");
            Delay.Milliseconds(200);
            
            CustomActions.ClickIfExists(repo.Vertex.StoppingController.ControllerButtonOKInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 2m for the attribute 'Text' to equal the specified value 'Stopped'. Associated repository item: 'Vertex.VertexShellMainForm.LabelControllerRunning'", repo.Vertex.VertexShellMainForm.LabelControllerRunningInfo, new RecordItemIndex(4));
            repo.Vertex.VertexShellMainForm.LabelControllerRunningInfo.WaitForAttributeEqual(120000, "Text", "Stopped");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Stopped') on item 'Vertex.VertexShellMainForm.LabelControllerRunning'.", repo.Vertex.VertexShellMainForm.LabelControllerRunningInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.Vertex.VertexShellMainForm.LabelControllerRunningInfo, "Text", "Stopped");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vertex.ControllerSetup.ButtonOk' at Center.", repo.Vertex.ControllerSetup.ButtonOkInfo, new RecordItemIndex(6));
            repo.Vertex.ControllerSetup.ButtonOk.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
